OP_MOVE = 'OP_MOVE'
OP_LOADSTR = 'OP_LOADSTR'
OP_XOR = 'OP_XOR'
OP_CONCAT = 'OP_CONCAT'
OP_ENV = 'OP_ENV'
OP_LOADSTRING = 'OP_LOADSTRING'
OP_CALL = 'OP_CALL'
OP_HALT = 'OP_HALT'
OP_JMP = 'OP_JMP'
OP_TRASH = 'OP_TRASH'
OP_ADD = 'OP_ADD'
OP_REVXOR = 'OP_REVXOR'

OP_LIST = [OP_MOVE, OP_LOADSTR, OP_XOR, OP_CONCAT, OP_ENV, OP_LOADSTRING, OP_CALL, OP_HALT, OP_JMP, OP_TRASH, OP_ADD, OP_REVXOR]
